[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "coUntYMoMmoSgGKSdMbkbLWmmEY6Rwd5U4tKfigWQrX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/beeman/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"
